import pandas as pd
from alpha_research.includes import BroadcastData as BroadcastData, DurationType as DurationType, Index as Index, OptionType as OptionType, ProductType as ProductType, StrikeType as StrikeType, Ticker as Ticker

class ContractParser:
    ohlcv_df: pd.DataFrame
    date: str
    broadcast_data_path: str
    def __init__(self, date: str, indices_file_path: str = None, broadcast_data_path: str = None) -> None: ...
    def parse_single_token(self, token: str) -> Ticker | list[Ticker] | None: ...
    def parse_single_option_chain(self, option_chain: str) -> list[Ticker]: ...
    def parse_single_option_dynamic_chain(self, state_map_broadcast: dict[str, BroadcastData], option_chain: str) -> list[Ticker]: ...
    def parse_tokens(self, token_list: list[str]) -> list[Ticker]: ...
    def parse_option_chain(self, option_chain_list: list[str]) -> list[Ticker]: ...
    def parse_ticker_options(self, token_list: list[str], option_chain_list: list[str]): ...
    def parse_ticker_dynamic_options(self, state_map_broadcast: dict[str, BroadcastData], option_chain_dynamic_list: list[str]) -> dict[str, Ticker]: ...
    def parse_spot_tickers(self, option_chain_dynamic_list: list[str]) -> list[str]: ...
