import pandas as pd
from dataclasses import dataclass, field
from enum import Enum

class Exchange(Enum):
    NSE = 'NSE'
    BSE = 'BSE'
    OPRA = 'OPRA'

class Side(Enum):
    BUY = 'BUY'
    SELL = 'SELL'

class OptionType(Enum):
    CE = 'C'
    PE = 'P'
    STRADDLE = 'SE'
    INVALID = 'INVALID'

class DurationType(Enum):
    D = 'W'
    W = 'W'
    M = 'M'

class StrikeType(Enum):
    STATIC = 'Static'
    DYNAMIC = 'Dynamic'

class ProductType(Enum):
    EQ = 'EQ'
    OPT = 'OPT'
    FUT = 'FUT'
    SPOT = 'SPOT'

class Index(Enum):
    SPXW = 'SPX'

@dataclass
class Ticker:
    exchange: str
    parent_ticker: str
    product_type: ProductType
    duration_type: DurationType
    duration_length: int
    strike_type: StrikeType
    option_type: OptionType
    strike_price: float
    current_strike_price: float
    ticker_name: str
    def print_details(self) -> None: ...
    def get_current_strike_price(self) -> float: ...
    def get_strike_price(self) -> float: ...
    def get_ticker_name(self) -> str: ...
    def get_expiry(self, date: str, trading_day_df: pd.DataFrame = None) -> str: ...
    def create_and_get_ticker_name(self, date: str) -> str: ...
    def get_file_path(self, data_path: str, date: str, trading_day_df: pd.DataFrame = None, strike_price: float = None) -> str: ...

@dataclass
class Trade:
    ticker: Ticker
    side: Side
    price: float
    quantity: int
    timestamp: str

@dataclass
class Position:
    ticker: str
    tcost: float
    net_quantity: int = ...
    ltp: float = ...
    net_value: float = ...
    net_pnl: float = ...
    ltt: str = ...
    net_transaction_cost: float = ...
    net_realised_pnl: float = ...
    penalty: float = ...
    trades: list[Trade] = field(default_factory=list)
    pnl_list: list[float] = field(default_factory=list)
    quantity_list: list[int] = field(default_factory=list)
    def print_details(self) -> None: ...
    def update_ltp(self, ltp: float) -> None: ...
    def on_trade(self, price: float, quantity: int, timestamp: str) -> None: ...
    def add_penalty(self) -> None: ...

@dataclass
class PositionManager:
    tcost: float
    position_map: dict[str, Position] = field(default_factory=dict)
    def add_ticker(self, ticker: str) -> None: ...
    def update_ltp(self, ticker: str, ltp: float) -> None: ...
    def on_trade(self, ticker: str, price: float, quantity: int, timestamp: int) -> None: ...
    def add_penalty(self, ticker: str): ...
    def print_details(self) -> None: ...

@dataclass
class Data:
    ticker: str
    timestamp: int = ...
    last_quote_timestamp: int = ...
    last_trade_timestamp: int = ...
    bid_price: float = ...
    bid_qty: float = ...
    ask_price: float = ...
    ask_qty: float = ...
    ltp: float = ...
    ltq: float = ...
    total_trade_value: float = ...
    total_trade_qty: float = ...
    total_trade_valuewholeday: float = ...
    total_trade_qtywholeday: float = ...
    vvap: float = ...
    open: float = ...
    high: float = ...
    low: float = ...
    close: float = ...
    def update_from_csv_line(self, line: str): ...
    def clearInterval(self) -> None: ...

@dataclass
class BroadcastData:
    ticker: str
    timestamp: int = ...
    open: float = ...
    high: float = ...
    low: float = ...
    close: float = ...
    volume: float = ...
    volume_count: float = ...
    def update_from_csv_line(self, line: str): ...
    def get_json(self) -> str: ...

@dataclass
class BookQuote:
    ticker: str
    timestamp: int = ...
    event_timestamp: int = ...
    bid_price: float = ...
    bid_qty: float = ...
    ask_price: float = ...
    ask_qty: float = ...
    def get_json(self) -> str: ...

@dataclass
class TradeQuote:
    ticker: str
    timestamp: int = ...
    event_timestamp: int = ...
    ltp: float = ...
    ltq: float = ...
    def get_json(self) -> str: ...

@dataclass
class StraddleData:
    call_data: Data
    put_data: Data
